### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by andydj1985** [occ-ai/scoresight#1]
Unhandled exception in script
Failed to execute script 'camera_view' due to unhandled
exception: DLL load failed while importing QtGui: Impossibile
trovare la procedura specificata.
Traceback (most recent call last):
File "camera_view.py••, line 3, in «module>
ImpottError: DLL load failed while importing QtGui: Impossibile trov

**Comment by royshil** [comment]
Is this using version 0.0.2?

**Comment by andydj1985** [comment]
yesterday the only avaiable was the 0.0.1, today i installed the 0.0.2 ad now starts.
Thank you
