### ISSUE TITLE
Error in new version (0.0.7) on Windows upon bootup.

### ISSUE THREAD

**Issue by mitchellcrazyeye** [occ-ai/scoresight#17]
This is directly after clean install. 0.0.6 works.

This is also hidden by the ScoreSight "Initializing" screen, so that might be helpful to fix as well as the only way to see this is hovering over the icon to "peek" at the error. I can't move the initial screen.

![image](https://github.com/occ-ai/scoresight/assets/19811106/521b74bf-1a38-420f-92a0-bdae7849cc19)

**Comment by royshil** [comment]
fixed in #16 
releasing 0.0.7 again now

**Comment by royshil** [comment]
new v0.0.7 resolved it
