### ISSUE TITLE
Request - Individual Characters OCR

### ISSUE THREAD

**Issue by Pablonciox** [occ-ai/scoresight#3]
Hi, I would like to do a request, 
You should do a individual character recognition, for example, in a time segment, you select the digits, so the recognition is a lot precise.
Thanks

**Comment by jf-blanco** [comment]
If I'm not mistaken you can reshape the box for the OCR to match the desired size of the digit so you can configure them individually if wanted. Unless I misunderstood you.

**Comment by royshil** [comment]
this is possible by setting the detection crop to a single character

**Comment by Pablonciox** [comment]
I use vmix with these app, i think that i can't combine different fonts
I don't know if you understood me.
I mean, if you have a timer, you select every digit.
This is a feature that has scoreboard OCR, that makes the detection much more precise.

**Comment by Pablonciox** [comment]
![Screenshot 2018-10-13 23 20 25](https://github.com/occ-ai/scoresight/assets/168954722/78a9bc60-68aa-4a3a-96fc-d58ec7aca497)
I mean this, that automatically converts on the format decided

**Comment by jf-blanco** [comment]
It's a totally different approach. I don't know if that would be necessarily better in terms of performance. Anyway the system needs to process more detection signals.
