### ISSUE TITLE
Request - Recognize Balls, Strikes, Outs lights on a baseball scoreboard

### ISSUE THREAD

**Issue by ducaandr** [occ-ai/scoresight#4]
Common baseball scoreboards have lights for balls, strikes and outs. It would be great to have an option to pickup those settings and return the values. 

![image](https://github.com/occ-ai/scoresight/assets/4949740/a8ac22a7-fa0b-422d-bc01-76ee217f0b4a)
![image](https://github.com/occ-ai/scoresight/assets/4949740/24845875-ce49-46d6-a54c-0d5d96e2011d)

**Comment by royshil** [comment]
implemented in #15

**Comment by royshil** [comment]
added in 0.0.7
