### ISSUE TITLE
Request for Adding Multi-language (i18n) Support 

### ISSUE THREAD

**Issue by iCassius** [occ-ai/scoresight#5]
It is recommended to add multi-language support to the project to enhance the user experience and attract a wider audience.

At the same time, I can complete relevant translations into Chinese and am very happy to promote the project.

**Comment by jf-blanco** [comment]
I can help with Spanish if the developer thinks it's a good idea. 
I'm a titled translator. 
Puedo ayudar con el inglés si el desarrollador cree que es una buena idea. 
Soy un traductor titulado.

**Comment by ArieR1963** [comment]
I can do the Dutch

**Comment by jf-blanco** [comment]
That would be great. I can supervise the resulting translation 😉

**Comment by royshil** [comment]
@jf-blanco @iCassius @ArieR1963 can you all test the translations https://github.com/occ-ai/scoresight/actions/runs/9418672277 ?
i'd like to release this

**Comment by jf-blanco** [comment]
There are some missing translations:
The source dropdown is not translated. It should be:
Select a Source: Selecciona una fuente
HD WebCam; HD WebCam
vMix Video: vMix Video
vMix Video External 2: vMix Video External 2
vMix Video YV12: vMix Video YV12:
vMix Video External 2 YV12: vMix Video External 2 YV12
Open a Video File: Abrir archivo de video
URL Source: Fuente URL
Screen Capture: Captura de pantalla
And inside Screen Capture:
Screen Capture Selection: Selección de captura de pantalla
And the first option in the dropdown menu:
Capture the entire screen: Capturar pantalla completa.
Drag: Arrastrar

The field are also not translated:
Home Score: Marcador local
Away Score: Marcador visitante
Time: Tiempo
Period: Parte
Home Fouls: Faltas locales
Away Fouls: Faltas visitantes
Shot Clock: Posesión
Custom: Personalizado

Maybe I'm leaving some things left. But for now I dont have more time. If I detect something else I come back.

**Comment by ArieR1963** [comment]
Hi,

I have add some comments on file: translations/scoresight_nl_NL.ts

Language
Dutch: (Nederlands)

Home Score: Thuis Score
Away Score: Uit Score
Time: Tijd
Period: Periode
Home Fouls: Thuis Overtreding
Away Fouls: Uit Overtreding
Shot Clock: Schotklok
Custom: Aangepast

Change Translation from ... to ..
Remove leading 0s: Eerste nul verwijderen
Ordinal (1st, 2nd, ..): Volgorde (1e, 2e, ..)

Select Preset: Selecteren voorkeuze

At Binarize "Adaptive" change to "Aanpasbaar"

Dilate: Verbreden

General Scoreboard: Algemeen Scoreboard
General Fonts (English): Algemeen Lettertype (Engels)
General Scoreboard Large: Algemeen Scoreboard Groot

Resume updates: Hervat updates


Regards,
Arie
Op vr 7 jun 2024 om 21:16 schreef jf_blanco ***@***.***>:

**Comment by royshil** [comment]
added in v0.0.7
